name: Release

on:
  push:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.13

      - name: Install Dependencies
        run: npm ci

      - name: Run prepublish steps
        run: npm run prepublishOnly

      - name: git-publish
        run: |
          git config user.email "ci@grafbase.com"
          git config user.name "CI"
          cd packages/miniflare
          npx git-publish --remote https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY} --branch build-${GITHUB_REF_NAME}
